// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlshiirummqvclwojiqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sc2hpaXJ1bW1xdmNsd29qaXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjcyODMsImV4cCI6MjA3Mzk0MzI4M30.8ktoNIVVzgjpmPP3cPDYF3OO6GtxJGRyj7ABTC1l8pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});